# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShipmentReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.CharField(max_length=64, unique=True)),
                ("address", models.CharField(blank=True, max_length=512)),
                ("status", models.CharField(default="reserved", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "ship_reservation"},
        ),
    ]
