# Generated by Django 4.2.29 on 2026-03-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentreservation',
            name='shipper',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
